CREATE USER ${DB_REPL_USER} REPLICATION LOGIN PASSWORD '${DB_REPL_PASSWORD}';
SELECT pg_create_physical_replication_slot('replication_slot');

GRANT CONNECT ON DATABASE ${DB_DATABASE} TO ${DB_REPL_USER};
GRANT USAGE ON SCHEMA public TO ${DB_REPL_USER};
GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${DB_REPL_USER};

--CREATE DATABASE ${DB_DATABASE};

-- Создание таблиц, если они не существуют
CREATE TABLE IF NOT EXISTS phone (id SERIAL PRIMARY KEY, phone_number VARCHAR(100) NOT NULL);

CREATE TABLE IF NOT EXISTS email (id SERIAL PRIMARY KEY, email VARCHAR(100) NOT NULL);
